name: Check pull request

on:
  pull_request:
    branches: [master, develop]

env:
  NODE_VERSION: 18
  RETENTION_DAYS: 30

jobs:
  install:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.cache-key }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - id: cache-key
        run: echo "::set-output name=cache-key::$(echo ${{ runner.os }}-node-${{ env.NODE_VERSION }}-npm-cache-$(sha256sum package-lock.json | cut -d' ' -f1))"
      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ steps.cache-key.outputs.cache-key }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE_VERSION }}-npm-cache-
      - run: npm ci

  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ needs.install.outputs.cache-key }}
      - run: npm run lint
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lint-report
          path: lint-report/
          retention-days: ${{ env.RETENTION_DAYS }}

  performance:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ needs.install.outputs.cache-key }}
      - run: npm run performance
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: performance-report
          path: performance-report/
          retention-days: ${{ env.RETENTION_DAYS }}

  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ needs.install.outputs.cache-key }}
      - run: npm run test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report
          path: test-report/
          retention-days: ${{ env.RETENTION_DAYS }}

  build:
    needs: [install, lint, performance, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ needs.install.outputs.cache-key }}
      - run: npm run build
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-report
          path: build-report/
          retention-days: ${{ env.RETENTION_DAYS }}
